---
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: ruby:2.4.4-alpine
        environment:
          RAILS_ENV: test
    steps:
      - run:
          name: Install system dependencies
          command: apk add --no-cache build-base git openssh-client
      - checkout
      - restore_cache:
          keys:
          - bundle-{{ "Gemfile" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --jobs 4 --retry 3
      - save_cache:
          key: bundle-{{ "Gemfile" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle
      - run:
          name: Run Tests
          command: COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN bundle exec rake
